[package]
name = "backend"
version = "0.1.0"
edition = "2024"

[dependencies]
dioxus = { workspace = true, features = ["server"] }
axum = { workspace = true }
tokio = { workspace = true }
ui = { workspace = true, features = ["server"] }
tower-sessions = { workspace = true }
